# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fe3cd1e9d053b0b0c13b46ab04f64c69455ef89789544a1db271f948e7411a8137f7490cf96e11455d30b041c8c34950cb21d172d14be9f9358e0a1135b26f0

test:
  secret_key_base: 5a9e25821c2a82865baa0e3c38ac8112e8db189d497d306ec66f502533eda20248b9b86962dac0e2d9ed9255b5966cde8b138353e0a834765da76d21c78b0c2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
